'use client';

import { ArrowRight, ArrowUpRight, Folder, FolderPlus, MoreHorizontal, Plus, Search } from 'lucide-react';
import { useState } from 'react';
import type { Project } from '@/lib/contracts';
import { displayDate } from './api';
import { Button, EmptyState, LoadingState } from './ui';

export function Projects({ projects, currentId, loading, onCreate, onOpen }: { projects: Project[]; currentId?: string; loading: boolean; onCreate: () => void; onOpen: (project: Project) => void }) {
  const [query, setQuery] = useState(''); const visible = projects.filter(p => `${p.name} ${p.description}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="projects-view view-enter"><div className="page-heading"><div><p className="eyebrow">03 / COLLECT THE CONTEXT</p><h1>Projects<span className="heading-count">{projects.length}</span></h1><p>A focused place for sources, questions, and findings.</p></div><Button onClick={onCreate}><Plus size={15} />New project</Button></div><div className="projects-subheading"><p>Keep the evidence together.<br /><span>Build understanding over time.</span></p><div className="small-search"><Search size={15} /><input aria-label="Filter projects" value={query} onChange={e => setQuery(e.target.value)} placeholder="Find a project…" /></div></div>{loading ? <LoadingState /> : !projects.length ? <div className="projects-empty"><EmptyState title="Make room for your next question." description="Create a project, bring related documents into it, and turn a search into a lasting investigation." action={<Button onClick={onCreate}><FolderPlus size={15} />Create your first project</Button>} /><div className="project-structure" aria-hidden="true"><span className="eyebrow">A SINGLE THREAD OF WORK</span><div className="structure-root"><Folder size={21} strokeWidth={1.2} /><span>Project</span></div><div className="structure-branches"><span>Sources</span><span>Conversations</span><span>Findings</span><span>Notes</span></div></div></div> : visible.length === 0 ? <EmptyState small title="No project with that name." description="Try a different term or start a new project." action={<Button variant="secondary" onClick={() => setQuery('')}>Clear search</Button>} /> : <div className="projects-grid">{visible.map((project, i) => <button className={`project-card ${currentId === project.id ? 'project-current' : ''}`} key={project.id} onClick={() => onOpen(project)}><div className="project-card-top"><span>{String(i + 1).padStart(2, '0')} / INVESTIGATION</span><ArrowUpRight size={18} /></div><div className="project-folder"><Folder size={36} strokeWidth={1.15} /><span className="project-folder-lines" /></div><h2>{project.name}</h2><p>{project.description || 'A focused collection of source documents and findings.'}</p><footer><span>Updated {displayDate(project.updated_at)}</span><span>{currentId === project.id ? 'Current project' : 'Open workspace'} <ArrowRight size={13} /></span></footer></button>)}<button className="project-card new-project-card" onClick={onCreate}><Plus size={24} strokeWidth={1.2} /><h2>Begin another thread</h2><p>Create a project for a new question.</p></button></div>}</div>;
}
