import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFile,readdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const migrations=(await readdir(path.join(root,'drizzle'))).filter(v=>v.endsWith('.sql')).sort();
const sql=(await Promise.all(migrations.map(v=>readFile(path.join(root,'drizzle',v),'utf8')))).join('\n');
function setup(){const d=new DatabaseSync(':memory:');d.exec('PRAGMA foreign_keys=ON;');d.exec(sql);return d;}
function seed(d){
 const stamp='2026-10-07T00:00:00.000Z';
 d.prepare('INSERT INTO projects(id,owner_id,name,created_at,updated_at) VALUES(?,?,?,?,?)').run('project-a','owner-a','Synthetic A',stamp,stamp);
 d.prepare('INSERT INTO documents(id,owner_id,title,filename,content_type,family_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run('doc-a','owner-a','Synthetic doc','synthetic.txt','text/plain','family-a',stamp,stamp);
 return stamp;
}
test('actual migration creates required durable tables',()=>{
 const d=setup();try{const names=d.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(v=>v.name);for(const name of ['projects','documents','project_documents','pages','chunks','tasks','chats','chat_messages','chat_message_parts','chat_jobs','chat_job_sources','artifacts','notes','analysis_jobs','ai_usage'])assert.ok(names.includes(name),name);}finally{d.close();}
});
test('source page and project membership pairs cannot duplicate or reference absent sources',()=>{
 const d=setup();try{const stamp=seed(d);const p=d.prepare('INSERT INTO pages(id,document_id,page_number,text,markdown,created_at) VALUES(?,?,?,?,?,?)');p.run('page-a','doc-a',1,'Synthetic','Synthetic',stamp);assert.throws(()=>p.run('page-duplicate','doc-a',1,'Duplicate','Duplicate',stamp));assert.throws(()=>p.run('page-foreign','missing-doc',1,'Absent','Absent',stamp));const member=d.prepare('INSERT INTO project_documents(project_id,document_id,added_at) VALUES(?,?,?)');member.run('project-a','doc-a',stamp);assert.throws(()=>member.run('project-a','doc-a',stamp));assert.throws(()=>member.run('project-a','missing-doc',stamp));}finally{d.close();}
});
test('chat envelopes, parts and accepted job sources preserve sequence/uniqueness',()=>{
 const d=setup();try{const stamp=seed(d);d.prepare('INSERT INTO chats(id,owner_id,project_id,title,created_at,updated_at) VALUES(?,?,?,?,?,?)').run('chat-a','owner-a','project-a','Synthetic chat',stamp,stamp);const message=d.prepare('INSERT INTO chat_messages(id,chat_id,role,sequence,created_at) VALUES(?,?,?,?,?)');message.run('request-a','chat-a','user',1,stamp);message.run('response-a','chat-a','assistant',2,stamp);assert.throws(()=>message.run('duplicate','chat-a','assistant',2,stamp));const part=d.prepare('INSERT INTO chat_message_parts(id,message_id,sequence,type,text) VALUES(?,?,?,?,?)');part.run('part-a','response-a',1,'text','Synthetic');assert.throws(()=>part.run('part-b','response-a',1,'text','Duplicate'));const job=d.prepare('INSERT INTO chat_jobs(id,owner_id,chat_id,request_message_id,response_message_id,request_text,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)');job.run('job-a','owner-a','chat-a','request-a','response-a','Synthetic question',stamp,stamp);assert.throws(()=>job.run('job-b','owner-a','chat-a','request-a','response-a','Duplicate question',stamp,stamp));const snapshot=d.prepare('INSERT INTO chat_job_sources(job_id,document_id,source_sha256) VALUES(?,?,?)');snapshot.run('job-a','doc-a','source-hash');assert.throws(()=>snapshot.run('job-a','doc-a','changed-hash'));assert.throws(()=>snapshot.run('job-a','missing-doc','bad'));}finally{d.close();}
});
test('database guards reject invalid statuses and immutable-owner changes',()=>{
 const d=setup();try{const stamp=seed(d);assert.throws(()=>d.prepare("UPDATE documents SET status='done' WHERE id='doc-a'").run(),/canonical status/);assert.throws(()=>d.prepare("UPDATE projects SET owner_id='owner-b' WHERE id='project-a'").run(),/ownership is immutable/);assert.throws(()=>d.prepare('INSERT INTO tasks(id,owner_id,status,created_at,updated_at) VALUES(?,?,?,?,?)').run('task-bad','owner-a','working',stamp,stamp),/canonical status/);}finally{d.close();}
});
test('database guards reject cross-owner project/source/note/job links',()=>{
 const d=setup();try{const stamp=seed(d);d.prepare('INSERT INTO projects(id,owner_id,name,created_at,updated_at) VALUES(?,?,?,?,?)').run('project-b','owner-b','Synthetic B',stamp,stamp);assert.throws(()=>d.prepare('INSERT INTO project_documents(project_id,document_id,added_at) VALUES(?,?,?)').run('project-b','doc-a',stamp),/ownership must match/);assert.throws(()=>d.prepare('INSERT INTO notes(id,owner_id,project_id,title,created_at,updated_at) VALUES(?,?,?,?,?,?)').run('note-b','owner-b','project-a','Cross owner',stamp,stamp),/ownership must match/);assert.throws(()=>d.prepare('INSERT INTO tasks(id,owner_id,document_id,created_at,updated_at) VALUES(?,?,?,?,?)').run('task-b','owner-b','doc-a',stamp,stamp),/ownership must match/);}finally{d.close();}
});
test('only one source task processes per owner; separate owners remain independent',()=>{
 const d=setup();try{const stamp=seed(d);const q=d.prepare('INSERT INTO tasks(id,owner_id,status,created_at,updated_at) VALUES(?,?,?,?,?)');q.run('task-a','owner-a','processing',stamp,stamp);assert.throws(()=>q.run('task-a2','owner-a','processing',stamp,stamp),/Only one source task/);q.run('task-b','owner-b','processing',stamp,stamp);assert.equal(d.prepare("SELECT COUNT(*) AS n FROM tasks WHERE status='processing'").get().n,2);}finally{d.close();}
});
test('database citation identity and immutable job snapshot reject forged updates',()=>{
 const d=setup();try{const stamp=seed(d);d.prepare('INSERT INTO pages(id,document_id,page_number,text,markdown,created_at) VALUES(?,?,?,?,?,?)').run('page-a','doc-a',1,'Synthetic source text','Synthetic source text',stamp);d.prepare('INSERT INTO chunks(id,document_id,page_id,page_number,sequence,text,created_at) VALUES(?,?,?,?,?,?,?)').run('chunk-a','doc-a','page-a',1,0,'Synthetic source text',stamp);assert.throws(()=>d.prepare('INSERT INTO chunks(id,document_id,page_id,page_number,sequence,text,created_at) VALUES(?,?,?,?,?,?,?)').run('chunk-wrong','doc-a','page-a',2,1,'Wrong page',stamp),/source page/);d.prepare('INSERT INTO chats(id,owner_id,title,created_at,updated_at) VALUES(?,?,?,?,?)').run('chat-a','owner-a','Synthetic chat',stamp,stamp);d.prepare('INSERT INTO chat_messages(id,chat_id,role,sequence,created_at) VALUES(?,?,?,?,?)').run('user-a','chat-a','user',1,stamp);d.prepare('INSERT INTO chat_messages(id,chat_id,role,sequence,created_at) VALUES(?,?,?,?,?)').run('assistant-a','chat-a','assistant',2,stamp);d.prepare('INSERT INTO chat_jobs(id,owner_id,chat_id,request_message_id,response_message_id,request_text,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run('job-a','owner-a','chat-a','user-a','assistant-a','Synthetic question',stamp,stamp);d.prepare('INSERT INTO chat_job_sources(job_id,document_id,source_sha256) VALUES(?,?,?)').run('job-a','doc-a','source-hash');assert.throws(()=>d.prepare("UPDATE chat_job_sources SET source_sha256='different' WHERE job_id='job-a'").run(),/immutable/);const p=d.prepare('INSERT INTO chat_message_parts(id,message_id,sequence,type,text,citation_document_id,citation_page_number,citation_chunk_id,citation_quote) VALUES(?,?,?,?,?,?,?,?,?)');p.run('citation-valid','assistant-a',1,'citation','','doc-a',1,'chunk-a','Synthetic source');assert.throws(()=>p.run('citation-forged','assistant-a',2,'citation','','doc-a',2,'chunk-a','Synthetic source'),/owned source passage/);}finally{d.close();}
});
